// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Prisma CLI (migrate, db push, etc.) needs a direct Postgres URL.
 * Pooled hosts (pooled.db.prisma.io) break session advisory locks → P1002.
 *
 * App runtime still uses DATABASE_URL (pooled) in src/lib/prisma.ts.
 */
function cleanEnvUrl(value: string | undefined): string | undefined {
  if (!value) return undefined;
  let url = value.trim();
  // Vercel/env pastes sometimes keep surrounding quotes in the value.
  if (
    (url.startsWith('"') && url.endsWith('"')) ||
    (url.startsWith("'") && url.endsWith("'"))
  ) {
    url = url.slice(1, -1).trim();
  }
  return url || undefined;
}

function isPostgresUrl(url: string): boolean {
  return /^postgres(ql)?:\/\//i.test(url);
}

function resolveMigrateUrl(): string | undefined {
  const direct = cleanEnvUrl(process.env.DIRECT_URL);
  if (direct && isPostgresUrl(direct)) {
    return direct;
  }

  const databaseUrl = cleanEnvUrl(process.env.DATABASE_URL);
  if (!databaseUrl) return undefined;

  // Derive a direct Prisma Postgres host when only the pooled URL is set.
  if (databaseUrl.includes("@pooled.db.prisma.io")) {
    return databaseUrl.replace("@pooled.db.prisma.io", "@db.prisma.io");
  }

  return databaseUrl;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveMigrateUrl(),
  },
});
